### ISSUE TITLE
where is the example data: m150206_s1_p0_1_ccs_minpass_2_minprdaccry_99.fastq.gz

### ISSUE THREAD

**Issue by Wadauk** [benjjneb/LRASManuscript#1]
As shown in the page: DADA2 + PacBio: S. aureus from Wagner et al. 2016, there is an example data. How to download it?
> fn <- file.path(path, "m150206_s1_p0_1_ccs_minpass_2_minprdaccry_99.fastq.gz")

**Comment by benjjneb** [comment]
The data from Wagner et al. is available from the European Nucleotide Archive under the study accession # PRJEB13979

https://www.ebi.ac.uk/ena/data/view/PRJEB13979

**Comment by Wadauk** [comment]
Thank you very much!
