### ISSUE TITLE
SRA accession

### ISSUE THREAD

**Issue by jordanvillalobos** [benjjneb/LRASManuscript#3]
Hello,
I am wondering if you could help me with the SRA accession to get the data files.
Thanks,

**Comment by benjjneb** [comment]
The SRA files aren't public yet, but you can follow along all the analyses from the processed data files stored as .rds objects and included in the repository. You'd just start at the point in each workflow where the `readRDS` commands are located.

**Comment by jordanvillalobos** [comment]
> The SRA files aren't public yet, but you can follow along all the analyses from the processed data files stored as .rds objects and included in the repository. You'd just start at the point in each workflow where the `readRDS` commands are located.

**Comment by splaisan** [comment]
Hi @benjjneb !
Thanks for the great resource, are there any news about the availability of the read data at SRA?
I could not find a hifi SRA dataset for the V1V9 amplicon from the zymo mock and this would be great to have for tools / tutorial evaluation.
thanks in advance

**Comment by benjjneb** [comment]
Yes, the accession is listed in the published manuscript:

> Sequencing data are deposited in the SRA under Bioproject accession PRJNA521754.
